version: "3.9"
services:
  frontend:
    build: .
    container_name: patient-frontend
    ports:
      - "10080:80"           # host:container
    environment:
      API_BASE: "https://patientbackend.isaachahn.my.id"   # your backendâ€™s local host:port
    restart: unless-stopped
